export const COUNTRIES = [
  { code: 'AFG', name: 'Afganistán' },
  { code: 'AGO', name: 'Angola' },
  { code: 'ARE', name: 'Emiratos Árabes Unidos' },
  { code: 'AUS', name: 'Australia' },
  { code: 'AUT', name: 'Austria' },
  { code: 'AZE', name: 'Azerbaiyán' },
  { code: 'BDI', name: 'Burundi' },
  { code: 'BEL', name: 'Bélgica' },
  { code: 'BEN', name: 'Benín' },
  { code: 'BFA', name: 'Burkina Faso' },
  { code: 'BGD', name: 'Bangladés' },
  { code: 'BGR', name: 'Bulgaria' },
  { code: 'BLR', name: 'Bielorrusia' },
  { code: 'BOL', name: 'Bolivia' },
  { code: 'BRA', name: 'Brasil' },
  { code: 'CAN', name: 'Canadá' },
  { code: 'CHE', name: 'Suiza' },
  { code: 'CHL', name: 'Chile' },
  { code: 'CHN', name: 'China' },
  { code: 'CIV', name: 'Costa de Marfil' },
  { code: 'CMR', name: 'Camerún' },
  { code: 'COD', name: 'República Democrática del Congo' },
  { code: 'COL', name: 'Colombia' },
  { code: 'CUB', name: 'Cuba' },
  { code: 'CZE', name: 'Chequia' },
  { code: 'DEU', name: 'Alemania' },
  { code: 'DOM', name: 'República Dominicana' },
  { code: 'ECU', name: 'Ecuador' },
  { code: 'EGY', name: 'Egipto' },
  { code: 'ESP', name: 'España' },
  { code: 'ETH', name: 'Etiopía' },
  { code: 'FRA', name: 'Francia' },
  { code: 'GBR', name: 'Reino Unido' },
  { code: 'GHA', name: 'Ghana' },
  { code: 'GIN', name: 'Guinea' },
  { code: 'GNB', name: 'Guinea-Bisáu' },
  { code: 'GRC', name: 'Grecia' },
  { code: 'GTM', name: 'Guatemala' },
  { code: 'HKG', name: 'Hong Kong' },
  { code: 'HND', name: 'Honduras' },
  { code: 'HTI', name: 'Haití' },
  { code: 'HUN', name: 'Hungría' },
  { code: 'IDN', name: 'Indonesia' },
  { code: 'IND', name: 'India' },
  { code: 'IRN', name: 'Irán' },
  { code: 'IRQ', name: 'Irak' },
  { code: 'ISR', name: 'Israel' },
  { code: 'ITA', name: 'Italia' },
  { code: 'JOR', name: 'Jordania' },
  { code: 'JPN', name: 'Japón' },
  { code: 'KAZ', name: 'Kazajistán' },
  { code: 'KEN', name: 'Kenia' },
  { code: 'KHM', name: 'Camboya' },
  { code: 'KOR', name: 'Corea del Sur' },
  { code: 'LAO', name: 'Laos' },
  { code: 'LKA', name: 'Sri Lanka' },
  { code: 'MAR', name: 'Marruecos' },
  { code: 'MDG', name: 'Madagascar' },
  { code: 'MEX', name: 'México' },
  { code: 'MLI', name: 'Malí' },
  { code: 'MMR', name: 'Birmania' },
  { code: 'MOZ', name: 'Mozambique' },
  { code: 'MWI', name: 'Malaui' },
  { code: 'MYS', name: 'Malasia' },
  { code: 'NGA', name: 'Nigeria' },
  { code: 'NIC', name: 'Nicaragua' },
  { code: 'NIG', name: 'Níger' },
  { code: 'NLD', name: 'Países Bajos' },
  { code: 'NPL', name: 'Nepal' },
  { code: 'PAK', name: 'Pakistán' },
  { code: 'PER', name: 'Perú' },
  { code: 'PHL', name: 'Filipinas' },
  { code: 'PNG', name: 'Papúa Nueva Guinea' },
  { code: 'POL', name: 'Polonia' },
  { code: 'PRK', name: 'Corea del Norte' },
  { code: 'PRT', name: 'Portugal' },
  { code: 'ROU', name: 'Rumanía' },
  { code: 'RUS', name: 'Rusia' },
  { code: 'RWA', name: 'Ruanda' },
  { code: 'SAU', name: 'Arabia Saudita' },
  { code: 'SDN', name: 'Sudán' },
  { code: 'SEN', name: 'Senegal' },
  { code: 'SLV', name: 'El Salvador' },
  { code: 'SOM', name: 'Somalia' },
  { code: 'SRB', name: 'Serbia' },
  { code: 'SWE', name: 'Suecia' },
  { code: 'SYR', name: 'Siria' },
  { code: 'TCD', name: 'Chad' },
  { code: 'THA', name: 'Tailandia' },
  { code: 'TJK', name: 'Tayikistán' },
  { code: 'TUN', name: 'Túnez' },
  { code: 'TUR', name: 'Turquía' },
  { code: 'TZA', name: 'Tanzania' },
  { code: 'UGA', name: 'Uganda' },
  { code: 'UKR', name: 'Ucrania' },
  { code: 'USA', name: 'Estados Unidos' },
  { code: 'UZB', name: 'Uzbekistán' },
  { code: 'VEN', name: 'Venezuela' },
  { code: 'VNM', name: 'Vietnam' },
  { code: 'YEM', name: 'Yemen' },
  { code: 'ZAF', name: 'Sudáfrica' },
  { code: 'ZMB', name: 'Zambia' },
  { code: 'ZWE', name: 'Zimbabue' }
];
